# 1.

¿Un subespacio puede tener dimensión 0?

## Verdadero ✓

El **subespacio trivial** $S = \{\mathbf{0}\}$ tiene dimensión 0.

---

### ¿De dónde vienen los axiomas?

Un subconjunto $S$ de un espacio vectorial $V$ es un **subespacio** si y solo si cumple tres condiciones. Estas condiciones son la definición formal de subespacio (Axler, *Linear Algebra Done Right*, Cap. 1):

| # | Axioma | Intuición |
|---|--------|-----------|
| 1 | **Contiene al vector cero:** $\mathbf{0} \in S$ | Todo subespacio debe incluir el origen. Sin esto, no podría ser cerrado bajo multiplicación escalar (si $c=0$, $c \cdot v = \mathbf{0}$). |
| 2 | **Cerrado bajo suma:** si $u, v \in S$ entonces $u + v \in S$ | Sumar dos vectores del subespacio no puede "salirse" de él. |
| 3 | **Cerrado bajo multiplicación escalar:** si $v \in S$ y $c \in \mathbb{R}$, entonces $c \cdot v \in S$ | Escalar un vector del subespacio no puede "salirse" de él. |

---

### Dimensión

La **dimensión** de un subespacio responde a la pregunta: *¿cuántas direcciones independientes hacen falta para describir todo el subespacio?*

Para entenderlo necesitamos dos conceptos previos:

**1. Independencia lineal**
Un conjunto de vectores $\{v_1, v_2, \ldots, v_k\}$ es **linealmente independiente** si ninguno de ellos puede escribirse como combinación de los demás. Formalmente:

$$c_1 v_1 + c_2 v_2 + \cdots + c_k v_k = \mathbf{0} \implies c_1 = c_2 = \cdots = c_k = 0$$

Ejemplo en $\mathbb{R}^2$: los vectores $(1,0)$ y $(0,1)$ son LI porque ninguno es múltiplo del otro. En cambio $(1,0)$ y $(2,0)$ **no** son LI porque $(2,0) = 2 \cdot (1,0)$.

**2. Base**
Una **base** de un subespacio $S$ es un conjunto de vectores que:
- Son linealmente independientes, **y**
- Generan todo $S$ (cualquier vector de $S$ se puede escribir como combinación lineal de ellos).

Ejemplo: la base estándar de $\mathbb{R}^3$ es $\{(1,0,0),\,(0,1,0),\,(0,0,1)\}$.

**3. Dimensión**
$$\dim(S) = \text{número de vectores en cualquier base de } S$$

Todas las bases de un mismo subespacio tienen la misma cantidad de vectores, por eso la dimensión está bien definida.

| Subespacio | Ejemplo de base | Dimensión |
|------------|-----------------|-----------|
| $\{\mathbf{0}\}$ (trivial) | $\emptyset$ | 0 |
| Una recta por el origen en $\mathbb{R}^3$ | $\{(1,2,3)\}$ | 1 |
| Un plano por el origen en $\mathbb{R}^3$ | $\{(1,0,0),(0,1,0)\}$ | 2 |
| $\mathbb{R}^3$ completo | $\{(1,0,0),(0,1,0),(0,0,1)\}$ | 3 |

**¿Por qué el subespacio trivial tiene dimensión 0?**
El vector cero nunca puede ser parte de una base porque viola la independencia lineal: $1 \cdot \mathbf{0} = \mathbf{0}$ con coeficiente $c=1 \neq 0$. Por lo tanto su base es el conjunto vacío $\emptyset$, que tiene 0 elementos:

$$\dim(\{\mathbf{0}\}) = |\emptyset| = 0$$

In [53]:
import numpy as np

# ── Definición del subespacio trivial ─────────────────────────────────────────
# El único vector que vive en este subespacio es el vector cero.
# Usamos R^3 como espacio ambiente (pero aplica a cualquier R^n).
zero = np.array([0, 0, 0])

print("=== Subespacio trivial S = {0} ===")
print(f"Vector: {zero}\n")

# ── Axioma 1: contiene al vector cero ─────────────────────────────────────────
# np.all() devuelve True si TODOS los elementos cumplen la condición.
print(f"Axioma 1 — contiene al vector cero: {np.all(zero == 0)}")

# ── Axioma 2: cerrado bajo suma ───────────────────────────────────────────────
# El único par posible dentro de S es (0, 0). Su suma debe seguir en S.
suma = zero + zero
print(f"Axioma 2 — 0 + 0 = {suma}  → sigue en S: {np.all(suma == 0)}")

# ── Axioma 3: cerrado bajo multiplicación escalar ─────────────────────────────
# Para cualquier escalar c, c·0 = 0. Lo probamos con varios valores de c.
print("Axioma 3 — multiplicación escalar:")
for c in [-3, 0, 5, 1.7]:
    resultado = c * zero
    print(f"  {c} · 0 = {resultado}  → sigue en S: {np.all(resultado == 0)}")

# ── Cálculo de la dimensión con np.linalg.matrix_rank ─────────────────────────
#
# Estrategia: la dimensión de un subespacio = número de vectores
# linealmente independientes en su base = rango de la matriz
# cuyas FILAS son los vectores del subespacio.
#
# reshape(1, -1) convierte el vector 1D [0, 0, 0] en una matriz
# de 1 fila y 3 columnas:   [[0, 0, 0]]
# Esto es necesario porque matrix_rank espera una matriz 2D.
#
# np.linalg.matrix_rank cuenta cuántas filas (vectores) son
# linealmente independientes → ese número ES la dimensión.
# El vector cero nunca es linealmente independiente, así que el rango = 0.
M = zero.reshape(1, -1)          # [[0, 0, 0]]
print(f"\nMatriz con los vectores del subespacio:\n{M}")

dimension = np.linalg.matrix_rank(M)
print(f"\ndim(S) = rango(M) = {dimension}")
print("→ El subespacio trivial tiene dimensión 0  ✓")

=== Subespacio trivial S = {0} ===
Vector: [0 0 0]

Axioma 1 — contiene al vector cero: True
Axioma 2 — 0 + 0 = [0 0 0]  → sigue en S: True
Axioma 3 — multiplicación escalar:
  -3 · 0 = [0 0 0]  → sigue en S: True
  0 · 0 = [0 0 0]  → sigue en S: True
  5 · 0 = [0 0 0]  → sigue en S: True
  1.7 · 0 = [0. 0. 0.]  → sigue en S: True

Matriz con los vectores del subespacio:
[[0 0 0]]

dim(S) = rango(M) = 0
→ El subespacio trivial tiene dimensión 0  ✓


# 2. Sea el conjunto LD $G = \{(1,2,3),\,(6,5,1),\,(-9,-4,7),\,(3.4,7.5,11.9)\}$. Se propone elegir exactamente uno de los vectores $v \in G$ para eliminarlo, y así convertir a $G' = G - \{v\}$ en un conjunto LI. ¿Cuál/es de las siguientes opciones cumple con lo requerido?

a. $(3.4,\;7.5,\;11.9)$

b. Ninguna

c. $(6,5,1)$

d. $(-9,\,-4,\,7)$

e. $(1,2,3)$

## Conceptos necesarios

### Dependencia e independencia lineal (LD / LI)

Un conjunto de vectores $\{v_1, \ldots, v_k\}$ es **linealmente dependiente (LD)** si existen escalares $c_1, \ldots, c_k$, **no todos cero**, tales que:

$$c_1 v_1 + c_2 v_2 + \cdots + c_k v_k = \mathbf{0}$$

En términos prácticos: al menos uno de los vectores se puede escribir como **combinación lineal** de los demás.

Si la única solución es $c_1 = c_2 = \cdots = c_k = 0$, el conjunto es **linealmente independiente (LI)**.

---

### ¿Cómo verificar LI con matrices?

Ponemos los vectores como **filas** de una matriz $M$ y calculamos su **rango**:

$$\text{rank}(M) = \text{número de vectores LI en el conjunto}$$

- Si $\text{rank}(M) = k$ (igual al número de vectores) → conjunto **LI**
- Si $\text{rank}(M) < k$ → conjunto **LD** (hay redundancia)

---

### Restricción clave: dimensión del espacio ambiente

En $\mathbb{R}^n$, el máximo número de vectores LI es $n$.  
Por eso, **cualquier conjunto de más de $n$ vectores en $\mathbb{R}^n$ es siempre LD**.

En este problema: $G \subset \mathbb{R}^3$ tiene 4 vectores → necesariamente LD (confirmado por el enunciado).  
Al eliminar uno, quedan 3 vectores en $\mathbb{R}^3$. Para que sean LI necesitamos $\text{rank} = 3$.

---

### ¿Cuándo es imposible?

Si los 4 vectores de $G$ todos pertenecen a un subespacio de dimensión $\leq 2$, entonces **cualquier subconjunto de 3 también pertenece a ese subespacio** y tendrá rango $\leq 2$ → serán LD sin importar cuál eliminemos.

In [54]:
import numpy as np

v1 = np.array([1,   2,   3  ])
v2 = np.array([6,   5,   1  ])
v3 = np.array([-9, -4,   7  ])
v4 = np.array([3.4, 7.5, 11.9])

G = {"(1,2,3)": v1, "(6,5,1)": v2, "(-9,-4,7)": v3, "(3.4,7.5,11.9)": v4}

# ── Paso 1: confirmar que G es LD ─────────────────────────────────────────────
# Apilamos los 4 vectores como filas de una matriz y calculamos su rango.
# Si rango < 4, el conjunto es LD.
M_G = np.array([v1, v2, v3, v4])
rango_G = np.linalg.matrix_rank(M_G)
print(f"Rango de G completo: {rango_G}  (4 vectores, rango {rango_G} → LD ✓)")
print(f"→ El subespacio generado por G tiene dimensión {rango_G}.")
print(f"  Todos los vectores de G viven en un subespacio de dim={rango_G}, no en todo R^3.\n")

# ── Paso 2: probar cada eliminación ───────────────────────────────────────────
# Para cada vector candidato a eliminar, formamos G' con los 3 restantes,
# calculamos el rango de la matriz 3x3. Si rango = 3 → G' es LI.
col1, col2, col3 = "Vector eliminado", "Rango G'", "G' es LI?"
print(f"{col1:<22} {col2:<12} {col3}")
print("-" * 50)

for nombre, vector in G.items():
    restantes = [v for k, v in G.items() if k != nombre]
    M_prima = np.array(restantes)
    rango = np.linalg.matrix_rank(M_prima)
    es_li = "✓ SÍ" if rango == 3 else "✗ NO (rango insuficiente)"
    print(f"{nombre:<22} {rango:<12} {es_li}")

# ── Paso 3: explicar por qué ninguna opción funciona ─────────────────────────
print(f"\nNingún subconjunto de 3 vectores de G es LI.")
print(f"Todos pertenecen al mismo subespacio de dim={rango_G}.")
print("Para tener 3 vectores LI en R^3 necesitamos rango = 3.")

# ── Verificación extra: v3 y v4 como combinación lineal de v1 y v2 ────────────
# Si v3 = a*v1 + b*v2, resolvemos el sistema con lstsq.
# lstsq encuentra la solución de mínimos cuadrados; si el error es ~0,
# la combinación lineal exacta existe.
print("\n── Verificación: ¿cada vector es CL de v1 y v2? ──")
for nombre, target in [("v3=(-9,-4,7)", v3), ("v4=(3.4,7.5,11.9)", v4)]:
    A = np.column_stack([v1, v2])          # matriz con v1 y v2 como columnas
    coefs, _, _, _ = np.linalg.lstsq(A, target, rcond=None)
    error = np.linalg.norm(target - A @ coefs)
    print(f"  {nombre}: {coefs[0]:.4f}·v1 + {coefs[1]:.4f}·v2,  error={error:.2e}")

Rango de G completo: 2  (4 vectores, rango 2 → LD ✓)
→ El subespacio generado por G tiene dimensión 2.
  Todos los vectores de G viven en un subespacio de dim=2, no en todo R^3.

Vector eliminado       Rango G'     G' es LI?
--------------------------------------------------
(1,2,3)                2            ✗ NO (rango insuficiente)
(6,5,1)                2            ✗ NO (rango insuficiente)
(-9,-4,7)              2            ✗ NO (rango insuficiente)
(3.4,7.5,11.9)         2            ✗ NO (rango insuficiente)

Ningún subconjunto de 3 vectores de G es LI.
Todos pertenecen al mismo subespacio de dim=2.
Para tener 3 vectores LI en R^3 necesitamos rango = 3.

── Verificación: ¿cada vector es CL de v1 y v2? ──
  v3=(-9,-4,7): 3.0000·v1 + -2.0000·v2,  error=6.99e-15
  v4=(3.4,7.5,11.9): 4.0000·v1 + -0.1000·v2,  error=6.71e-15


## Respuesta: **b. Ninguna**

El código muestra que el rango de $G$ completo es **2**, no 3. Eso significa que los 4 vectores no llenan $\mathbb{R}^3$: todos viven dentro de un plano (subespacio de dimensión 2) que pasa por el origen.

**¿Por qué?** Porque $v_3$ y $v_4$ son combinaciones lineales de $v_1$ y $v_2$:

$$v_3 = 3\,v_1 - 2\,v_2 \qquad v_4 = 4\,v_1 - 0.1\,v_2$$

Al eliminar cualquier vector, los 3 restantes siguen estando en ese mismo plano de dimensión 2, por lo que su rango siempre será $\leq 2 < 3$ → siguen siendo LD.

Para obtener un conjunto LI de 3 vectores en $\mathbb{R}^3$ habría que **reemplazar** al menos un vector por uno que salga del plano generado por $v_1$ y $v_2$, no solo eliminar.

# 3.

Sea el conjunto LD $G = \{(2,3,4),\,(6,5,1),\,(7.4,\,11.5,\,16.9),\,(6.8,\,11,\,15.8)\}$. Se propone elegir exactamente uno de los vectores $v \in G$ para eliminarlo, y así convertir a $G' = G - \{v\}$ en un conjunto LI. ¿Cuál/es de las siguientes opciones cumple con lo requerido?

## Conceptos aplicados (igual que ejercicio 2)

Los conceptos de LD/LI, rango y dimensión son los mismos que en el ejercicio anterior.
La diferencia clave estará en el **rango de G**: si es 3, existe al menos un vector eliminable; si es 2 (como en el ejercicio 2), ninguno funciona.

In [55]:
import numpy as np

v1 = np.array([2,   3,   4  ])
v2 = np.array([6,   5,   1  ])
v3 = np.array([7.4, 11.5, 16.9])
v4 = np.array([6.8, 11.0, 15.8])

G = {"(2,3,4)": v1, "(6,5,1)": v2, "(7.4,11.5,16.9)": v3, "(6.8,11,15.8)": v4}

# ── Paso 1: rango de G completo ───────────────────────────────────────────────
M_G = np.array([v1, v2, v3, v4])
rango_G = np.linalg.matrix_rank(M_G)
print(f"Rango de G completo: {rango_G}  (4 vectores)")
if rango_G == 3:
    print("→ rango=3: los vectores SÍ llenan R^3.")
    print("  Hay redundancia (G es LD), pero al menos 3 son independientes.\n")
else:
    print(f"→ rango={rango_G}: todos viven en un subespacio de dim={rango_G}.\n")

# ── Paso 2: probar cada eliminación ───────────────────────────────────────────
col1, col2, col3 = "Vector eliminado", "Rango G'", "G' es LI?"
print(f"{col1:<22} {col2:<12} {col3}")
print("-" * 52)

candidatos_li = []
for nombre, vector in G.items():
    restantes = [v for k, v in G.items() if k != nombre]
    M_prima = np.array(restantes)
    rango = np.linalg.matrix_rank(M_prima)
    es_li = rango == 3
    estado = "✓ SÍ" if es_li else "✗ NO (rango insuficiente)"
    print(f"{nombre:<22} {rango:<12} {estado}")
    if es_li:
        candidatos_li.append(nombre)

print(f"\nVectores que se pueden eliminar para obtener G' LI: {candidatos_li}")

# ── Paso 3: identificar cuál vector es la "redundancia" ──────────────────────
# Un vector es redundante si está en el span de los demás.
# Eso ocurre cuando es combinación lineal de otros dos (aquí en R^3).
# Usamos lstsq para verificar: si error ≈ 0, es CL exacta.
print("\n── ¿Qué vector es combinación lineal de los otros? ──")
nombres = list(G.keys())
vectores = list(G.values())
for i, (nombre_t, target) in enumerate(G.items()):
    otros = [v for k, v in G.items() if k != nombre_t]
    # Buscamos si target = a*u1 + b*u2 + c*u3 (con los 3 restantes)
    A = np.column_stack(otros)
    coefs, _, _, _ = np.linalg.lstsq(A, target, rcond=None)
    error = np.linalg.norm(target - A @ coefs)
    es_cl = error < 1e-9
    print(f"  {nombre_t}: {'ES CL de los otros' if es_cl else 'NO es CL de los otros'}"
          f"  (error={error:.2e})")

Rango de G completo: 3  (4 vectores)
→ rango=3: los vectores SÍ llenan R^3.
  Hay redundancia (G es LD), pero al menos 3 son independientes.

Vector eliminado       Rango G'     G' es LI?
----------------------------------------------------
(2,3,4)                3            ✓ SÍ
(6,5,1)                3            ✓ SÍ
(7.4,11.5,16.9)        2            ✗ NO (rango insuficiente)
(6.8,11,15.8)          3            ✓ SÍ

Vectores que se pueden eliminar para obtener G' LI: ['(2,3,4)', '(6,5,1)', '(6.8,11,15.8)']

── ¿Qué vector es combinación lineal de los otros? ──
  (2,3,4): ES CL de los otros  (error=6.66e-16)
  (6,5,1): ES CL de los otros  (error=4.09e-14)
  (7.4,11.5,16.9): NO es CL de los otros  (error=2.77e-01)
  (6.8,11,15.8): ES CL de los otros  (error=1.17e-14)


## Respuesta

A diferencia del ejercicio 2, aquí el rango de $G$ es **3**, lo que significa que los 4 vectores sí generan $\mathbb{R}^3$ — solo hay **una** dirección redundante.

El vector redundante es $v_4 = (6.8, 11, 15.8)$, que es combinación lineal de $v_1$ y $v_2$:

$$v_4 = 4\,v_1 - 0.2\,v_2$$

**Conclusión:**

| Vector eliminado | $G'$ resultante | LI? | Motivo |
|-----------------|-----------------|-----|--------|
| $v_4 = (6.8,11,15.8)$ | $\{v_1, v_2, v_3\}$ | ✓ SÍ | $v_3$ aporta la tercera dirección independiente |
| $v_1 = (2,3,4)$ | $\{v_2, v_3, v_4\}$ | ✓ SÍ | Sin $v_1$, la relación $v_4=4v_1-0.2v_2$ ya no aplica |
| $v_2 = (6,5,1)$ | $\{v_1, v_3, v_4\}$ | ✓ SÍ | Sin $v_2$, ídem |
| $v_3 = (7.4,11.5,16.9)$ | $\{v_1, v_2, v_4\}$ | ✗ NO | $v_4=4v_1-0.2v_2$ → rango cae a 2 |

La dependencia $v_4 = 4v_1 - 0.2v_2$ requiere **tanto** $v_1$ como $v_2$. Eliminar cualquiera de los dos rompe esa relación. Solo eliminar $v_3$ falla, porque deja expuesta la dependencia entre $v_1$, $v_2$ y $v_4$.

**Diferencia clave con el ejercicio 2:** allí todos los vectores estaban en un plano (dim=2), por lo que era imposible elegir 3 LI. Aquí solo $v_3$ es el "vector indispensable" — eliminarlo colapsa el rango.

# 4. ¿Cuál es la dimensión de $\mathcal{P}_5[x]$?

## Respuesta: **6**

### ¿Qué es $\mathcal{P}_5[x]$?

$\mathcal{P}_5[x]$ es el **espacio vectorial de todos los polinomios de grado $\leq 5$** con coeficientes reales:

$$p(x) = a_0 + a_1 x + a_2 x^2 + a_3 x^3 + a_4 x^4 + a_5 x^5 \qquad a_i \in \mathbb{R}$$

Es un espacio vectorial porque cumple los axiomas: la suma de dos polinomios de grado $\leq 5$ sigue siendo de grado $\leq 5$, y multiplicar por un escalar tampoco sube el grado.

---

### Base de $\mathcal{P}_5[x]$

La **base estándar** (o base monomial) es:

$$\mathcal{B} = \{1,\; x,\; x^2,\; x^3,\; x^4,\; x^5\}$$

**¿Por qué es base?**
- **Generan todo $\mathcal{P}_5[x]$:** cualquier polinomio $p(x)$ es una combinación lineal $\sum_{i=0}^{5} a_i x^i$.
- **Son LI:** ningún monomio $x^k$ puede escribirse como combinación lineal de los otros (tienen grados distintos).

Como la base tiene **6 elementos**:

$$\dim(\mathcal{P}_5[x]) = 6$$

---

### Generalización

$$\dim(\mathcal{P}_n[x]) = n + 1$$

porque la base tiene los $n+1$ monomios $\{1, x, x^2, \ldots, x^n\}$.

In [56]:
import numpy as np

# En numpy, un polinomio se representa como un array de coeficientes.
# Convenio numpy: el índice i corresponde al coeficiente de x^i.
# Ej: p(x) = 3 + 0x + 5x^2 → np.array([3, 0, 5])

# ── Base estándar de P_5[x] ───────────────────────────────────────────────────
# Cada vector base es un polinomio con un solo coeficiente distinto de cero.
# Representamos cada monomio x^k como un vector de R^6 (6 coeficientes).
n = 5
base = np.eye(n + 1)   # matriz identidad 6x6: cada fila es un vector base

print("Base estándar de P_5[x] (cada fila = coeficientes de un monomio):")
print(f"{'Monomio':<8} {'Coeficientes [a0, a1, a2, a3, a4, a5]'}")
print("-" * 50)
for k in range(n + 1):
    monomio = f"x^{k}" if k > 1 else ("1" if k == 0 else "x")
    print(f"{monomio:<8} {base[k]}")

# ── Verificar LI: rango de la matriz base = número de vectores ────────────────
rango = np.linalg.matrix_rank(base)
print(f"\nRango de la matriz base: {rango}")
print(f"Número de vectores base: {n + 1}")
print(f"rango == n+1 → base es LI: {rango == n + 1}")

# ── Dimensión ─────────────────────────────────────────────────────────────────
dimension = rango
print(f"\ndim(P_5[x]) = {dimension}")

# ── Ejemplo: cualquier polinomio como CL de la base ──────────────────────────
print("\n── Ejemplo: p(x) = 2 - 3x + x^4 como CL de la base ──")
p = np.array([2, -3, 0, 0, 1, 0])   # coeficientes de p(x)
print(f"Coeficientes: {p}")
print("Reconstrucción: ", end="")
terminos = [f"({p[k]})·x^{k}" for k in range(n+1) if p[k] != 0]
print(" + ".join(terminos))

Base estándar de P_5[x] (cada fila = coeficientes de un monomio):
Monomio  Coeficientes [a0, a1, a2, a3, a4, a5]
--------------------------------------------------
1        [1. 0. 0. 0. 0. 0.]
x        [0. 1. 0. 0. 0. 0.]
x^2      [0. 0. 1. 0. 0. 0.]
x^3      [0. 0. 0. 1. 0. 0.]
x^4      [0. 0. 0. 0. 1. 0.]
x^5      [0. 0. 0. 0. 0. 1.]

Rango de la matriz base: 6
Número de vectores base: 6
rango == n+1 → base es LI: True

dim(P_5[x]) = 6

── Ejemplo: p(x) = 2 - 3x + x^4 como CL de la base ──
Coeficientes: [ 2 -3  0  0  1  0]
Reconstrucción: (2)·x^0 + (-3)·x^1 + (1)·x^4


# 5.

Para todo espacio vectorial (de dimensión positiva, con $K = \mathbb{R}$) hay infinitas bases posibles

## Verdadero ✓

### Argumento

Si $\{v_1, v_2, \ldots, v_n\}$ es una base de un espacio vectorial $V$ con $\dim(V) = n \geq 1$, entonces para cualquier escalar $c \neq 0$ el conjunto $\{c \cdot v_1,\; v_2,\; \ldots,\; v_n\}$ **también es una base**:

- **Sigue siendo LI:** si $\alpha_1 (c\,v_1) + \alpha_2 v_2 + \cdots + \alpha_n v_n = \mathbf{0}$, entonces $(\alpha_1 c)\,v_1 + \cdots = \mathbf{0}$, y como la base original es LI todos los coeficientes son 0, en particular $\alpha_1 c = 0 \Rightarrow \alpha_1 = 0$ (porque $c \neq 0$).
- **Sigue generando $V$:** el span no cambia porque $v_1 = \frac{1}{c}(c\,v_1)$, así que podemos recuperar $v_1$ y con él todo $V$.

Como $\mathbb{R}$ tiene **infinitos** escalares $c \neq 0$, obtenemos infinitas bases distintas.

> **Nota:** esto es exclusivo de campos infinitos como $\mathbb{R}$ o $\mathbb{C}$. Sobre un campo finito $\mathbb{F}_q$ el número de bases también es finito.

In [57]:
import numpy as np

# Demostración en R^2: generamos infinitas bases escalando v1
# Base canónica de R^2
v1 = np.array([1.0, 0.0])
v2 = np.array([0.0, 1.0])

print("Base canónica de R^2: {e1, e2}")
print(f"  e1 = {v1},  e2 = {v2}\n")

# Para cada c != 0, {c*v1, v2} es una base distinta.
# Verificamos LI mediante el determinante de la matriz [c*v1 | v2].
# det != 0  ↔  vectores LI  ↔  forman una base de R^2.
escalares = [0.5, 1, 2, -3, 100, np.pi, np.e]

print(f"{'c':<10} {'c·e1':<20} {'det([c·e1, e2])':<18} {'Es base?'}")
print("-" * 60)
for c in escalares:
    v1_escalado = c * v1
    # Armamos la matriz con los vectores como columnas y calculamos det
    M = np.column_stack([v1_escalado, v2])
    det = np.linalg.det(M)
    es_base = abs(det) > 1e-10
    print(f"{c:<10.4f} {str(v1_escalado):<20} {det:<18.4f} {'✓ Sí' if es_base else '✗ No'}")

print("\n→ Cualquier c ≠ 0 genera una base distinta.")
print(f"  Como ℝ tiene infinitos c ≠ 0, hay infinitas bases. ✓")

# ── Demostración más visual: bases en distintas direcciones ──────────────────
print("\n── Bases con rotación (también son bases válidas) ──")
print("Rotar los vectores base en un ángulo θ también da una base:")
for theta_deg in [30, 45, 60, 90]:
    theta = np.radians(theta_deg)
    # Matriz de rotación
    R = np.array([[np.cos(theta), -np.sin(theta)],
                  [np.sin(theta),  np.cos(theta)]])
    u1 = R @ v1
    u2 = R @ v2
    det = np.linalg.det(np.column_stack([u1, u2]))
    print(f"  θ={theta_deg}°: u1={np.round(u1,3)}, u2={np.round(u2,3)},  det={det:.4f}  ✓")

Base canónica de R^2: {e1, e2}
  e1 = [1. 0.],  e2 = [0. 1.]

c          c·e1                 det([c·e1, e2])    Es base?
------------------------------------------------------------
0.5000     [0.5 0. ]            0.5000             ✓ Sí
1.0000     [1. 0.]              1.0000             ✓ Sí
2.0000     [2. 0.]              2.0000             ✓ Sí
-3.0000    [-3. -0.]            -3.0000            ✓ Sí
100.0000   [100.   0.]          100.0000           ✓ Sí
3.1416     [3.14159265 0.        ] 3.1416             ✓ Sí
2.7183     [2.71828183 0.        ] 2.7183             ✓ Sí

→ Cualquier c ≠ 0 genera una base distinta.
  Como ℝ tiene infinitos c ≠ 0, hay infinitas bases. ✓

── Bases con rotación (también son bases válidas) ──
Rotar los vectores base en un ángulo θ también da una base:
  θ=30°: u1=[0.866 0.5  ], u2=[-0.5    0.866],  det=1.0000  ✓
  θ=45°: u1=[0.707 0.707], u2=[-0.707  0.707],  det=1.0000  ✓
  θ=60°: u1=[0.5   0.866], u2=[-0.866  0.5  ],  det=1.0000  ✓
  θ=90°: u1=[0. 1.]

# 6.

Sea la matriz $A = \begin{pmatrix} 1 & 3 & 2\\ 4 & 2 & -1\\ 5 & 5 & 1 \end{pmatrix}$. Hallar el rango $r(A)$.

## Respuesta: $r(A) = 2$

### ¿Qué es el rango de una matriz?

El **rango** de una matriz $A$ es el número de **filas (o columnas) linealmente independientes**. Equivalentemente, es la dimensión del espacio generado por sus filas (o columnas).

Se calcula llevando $A$ a su **forma escalonada** mediante eliminación gaussiana y contando las filas no nulas que quedan.

---

### Eliminación gaussiana a mano

$$A = \begin{pmatrix} 1 & 3 & 2\\ 4 & 2 & -1\\ 5 & 5 & 1 \end{pmatrix}$$

**Paso 1:** $F_2 \leftarrow F_2 - 4\,F_1$ y $F_3 \leftarrow F_3 - 5\,F_1$

$$\begin{pmatrix} 1 & 3 & 2\\ 0 & -10 & -9\\ 0 & -10 & -9 \end{pmatrix}$$

**Paso 2:** $F_3 \leftarrow F_3 - F_2$

$$\begin{pmatrix} 1 & 3 & 2\\ 0 & -10 & -9\\ 0 & 0 & 0 \end{pmatrix}$$

La forma escalonada tiene **2 filas no nulas** → $r(A) = 2$.

**Observación:** $F_3 = F_1 + F_2$ en la matriz original, por lo que la tercera fila es combinación lineal de las otras dos y no aporta una dirección independiente.

In [58]:
import numpy as np

A = np.array([[1,  3,  2],
              [4,  2, -1],
              [5,  5,  1]], dtype=float)

print("Matriz A:")
print(A)

# ── Rango con numpy ───────────────────────────────────────────────────────────
# matrix_rank usa SVD internamente: cuenta los valores singulares
# significativamente mayores que cero.
rango = np.linalg.matrix_rank(A)
print(f"\nr(A) = {rango}")

# ── Verificación: F3 = F1 + F2 ───────────────────────────────────────────────
print("\n── Verificación: ¿F3 es CL de F1 y F2? ──")
F1, F2, F3 = A[0], A[1], A[2]
print(f"F1 + F2 = {F1} + {F2} = {F1 + F2}")
print(f"F3      = {F3}")
print(f"F3 == F1 + F2: {np.allclose(F3, F1 + F2)}")

# ── Eliminación gaussiana paso a paso ────────────────────────────────────────
print("\n── Eliminación gaussiana ──")
M = A.copy()

print(f"Original:\n{M}\n")

M[1] = M[1] - 4 * M[0]   # F2 ← F2 - 4·F1
M[2] = M[2] - 5 * M[0]   # F3 ← F3 - 5·F1
print(f"Después de F2←F2-4F1 y F3←F3-5F1:\n{M}\n")

M[2] = M[2] - M[1]        # F3 ← F3 - F2
print(f"Después de F3←F3-F2 (forma escalonada):\n{M}")

filas_no_nulas = np.sum(~np.all(np.isclose(M, 0), axis=1))
print(f"\nFilas no nulas: {filas_no_nulas}  →  r(A) = {filas_no_nulas}")

Matriz A:
[[ 1.  3.  2.]
 [ 4.  2. -1.]
 [ 5.  5.  1.]]

r(A) = 2

── Verificación: ¿F3 es CL de F1 y F2? ──
F1 + F2 = [1. 3. 2.] + [ 4.  2. -1.] = [5. 5. 1.]
F3      = [5. 5. 1.]
F3 == F1 + F2: True

── Eliminación gaussiana ──
Original:
[[ 1.  3.  2.]
 [ 4.  2. -1.]
 [ 5.  5.  1.]]

Después de F2←F2-4F1 y F3←F3-5F1:
[[  1.   3.   2.]
 [  0. -10.  -9.]
 [  0. -10.  -9.]]

Después de F3←F3-F2 (forma escalonada):
[[  1.   3.   2.]
 [  0. -10.  -9.]
 [  0.   0.   0.]]

Filas no nulas: 2  →  r(A) = 2


# 7.

Toda matriz rectangular $A \in \mathbb{R}^{m \times n}$ con $m \neq n$ tiene nulidad positiva

a. Sí, pero sólo si $m > n$

b. Sí, pero sólo si $m < n$

c. No, nunca

## Respuesta: **b. Sí, pero sólo si $m < n$**

---

### Conceptos necesarios

**Nulidad** de $A$ es la dimensión del núcleo (espacio nulo):

$$\text{nulidad}(A) = \dim(\ker(A)) = \dim\{x \in \mathbb{R}^n : Ax = \mathbf{0}\}$$

**Teorema rango-nulidad** (fundamental del álgebra lineal):

$$\underbrace{r(A)}_{\text{rango}} + \underbrace{\text{nulidad}(A)}_{\dim(\ker A)} = n \quad \text{(número de columnas)}$$

Por lo tanto: $\text{nulidad}(A) = n - r(A)$. La nulidad es positiva si y solo si $r(A) < n$.

---

### Análisis por casos

**Caso $m < n$ (más columnas que filas):**

$$r(A) \leq \min(m, n) = m < n \implies \text{nulidad}(A) = n - r(A) \geq n - m > 0$$

La nulidad es **siempre positiva**: hay más incógnitas que ecuaciones, el sistema $Ax = 0$ siempre tiene soluciones no triviales.

**Caso $m > n$ (más filas que columnas):**

$$r(A) \leq \min(m, n) = n$$

Si $r(A) = n$ (rango columna completo), entonces $\text{nulidad}(A) = n - n = 0$.

Ejemplo: $A = \begin{pmatrix}1\\0\end{pmatrix} \in \mathbb{R}^{2 \times 1}$ tiene $r(A)=1$ y nulidad $= 1-1 = 0$.

In [59]:
import numpy as np

def analizar(A, nombre):
    m, n = A.shape
    rango = np.linalg.matrix_rank(A)
    nulidad = n - rango
    # Núcleo: vectores x tal que Ax = 0. scipy lo calcula, pero con numpy
    # usamos SVD: los vectores singulares derechos asociados a val. sing. ~0.
    _, s, Vt = np.linalg.svd(A)
    # Completamos con ceros si rango < n
    ker_basis = Vt[rango:].T   # columnas que forman base del núcleo
    print(f"{nombre}  shape={A.shape}  rango={rango}  nulidad={nulidad}  "
          f"(rango + nulidad = {rango}+{nulidad} = {rango+nulidad} = n={n})")
    if nulidad > 0:
        print(f"  Base del núcleo (verificación Ax≈0):")
        for v in ker_basis.T:
            print(f"    x={np.round(v,4)}  →  Ax={np.round(A@v,10)}")
    print()

# ── Caso m < n: nulidad siempre positiva ─────────────────────────────────────
print("=== Caso m < n (más columnas que filas) ===")
A1 = np.array([[1, 2, 3],
               [4, 5, 6]])           # 2×3
A2 = np.array([[1, 0, 0, 0]])        # 1×4 (rango máximo posible = 1)
A3 = np.array([[1, 2, 3, 4],
               [0, 1, 0, 1]])        # 2×4

analizar(A1, "A1 (2×3)")
analizar(A2, "A2 (1×4)")
analizar(A3, "A3 (2×4)")

# ── Caso m > n: nulidad puede ser 0 ──────────────────────────────────────────
print("=== Caso m > n (más filas que columnas) ===")
B1 = np.array([[1],
               [0]])                  # 2×1, rango=1, nulidad=0
B2 = np.array([[1, 0],
               [0, 1],
               [0, 0]])              # 3×2, rango=2, nulidad=0
B3 = np.array([[1, 2],
               [2, 4],
               [3, 6]])              # 3×2, rango=1, nulidad=1

analizar(B1, "B1 (2×1)")
analizar(B2, "B2 (3×2) rango completo")
analizar(B3, "B3 (3×2) rango incompleto")

=== Caso m < n (más columnas que filas) ===
A1 (2×3)  shape=(2, 3)  rango=2  nulidad=1  (rango + nulidad = 2+1 = 3 = n=3)
  Base del núcleo (verificación Ax≈0):
    x=[ 0.4082 -0.8165  0.4082]  →  Ax=[-0.  0.]

A2 (1×4)  shape=(1, 4)  rango=1  nulidad=3  (rango + nulidad = 1+3 = 4 = n=4)
  Base del núcleo (verificación Ax≈0):
    x=[0. 1. 0. 0.]  →  Ax=[0.]
    x=[0. 0. 1. 0.]  →  Ax=[0.]
    x=[0. 0. 0. 1.]  →  Ax=[0.]

A3 (2×4)  shape=(2, 4)  rango=2  nulidad=2  (rango + nulidad = 2+2 = 4 = n=4)
  Base del núcleo (verificación Ax≈0):
    x=[-0.7397  0.3389  0.4725 -0.3389]  →  Ax=[0. 0.]
    x=[-0.6079 -0.5494 -0.1636  0.5494]  →  Ax=[0. 0.]

=== Caso m > n (más filas que columnas) ===
B1 (2×1)  shape=(2, 1)  rango=1  nulidad=0  (rango + nulidad = 1+0 = 1 = n=1)

B2 (3×2) rango completo  shape=(3, 2)  rango=2  nulidad=0  (rango + nulidad = 2+0 = 2 = n=2)

B3 (3×2) rango incompleto  shape=(3, 2)  rango=1  nulidad=1  (rango + nulidad = 1+1 = 2 = n=2)
  Base del núcleo (verificación Ax≈