# Primer pregunta

Se propone el siguiente producto interno sobre $\mathbb{R}^2$:

$$\Phi(x,y) = 5x_1y_1 + x_1y_2 + x_2y_1 + 3x_2y_2$$

¿Es un producto interno válido?

## Respuesta: **Sí, es un producto interno válido**

Todo producto interno bilineal simétrico sobre $\mathbb{R}^n$ puede escribirse como:

$$\Phi(x, y) = x^\top A\, y \qquad \text{con} \qquad A = \begin{pmatrix} 5 & 1 \\ 1 & 3 \end{pmatrix}$$

Para que $\Phi$ sea un **producto interno válido** se deben cumplir dos condiciones (MML §3.2):

---

### Condición 1 — Simetría: $\Phi(x,y) = \Phi(y,x)$

$$\Phi(x,y) = 5x_1y_1 + \boldsymbol{x_1y_2 + x_2y_1} + 3x_2y_2 = \Phi(y,x) \quad \checkmark$$

Los coeficientes cruzados son iguales ($1 = 1$), por lo que $\Phi$ es simétrica.

---

### Condición 2 — Definición positiva: $\Phi(x,x) > 0$ para todo $x \neq \mathbf{0}$

Evaluamos la **forma cuadrática** $\Phi(x,x)$:

$$\Phi(x,x) = 5x_1^2 + 2x_1x_2 + 3x_2^2$$

Completando el cuadrado en $x_1$:

$$= 5\!\left(x_1 + \frac{x_2}{5}\right)^{\!2} - \frac{x_2^2}{5} + 3x_2^2 = 5\!\left(x_1 + \frac{x_2}{5}\right)^{\!2} + \frac{14}{5}\,x_2^2$$

Ambos términos son $\geq 0$, y se anulan simultáneamente **solo si** $x_1 = x_2 = 0$.  
Por lo tanto $\Phi(x,x) > 0$ para todo $x \neq \mathbf{0}$ $\checkmark$

---

**Conclusión:** $\Phi$ cumple simetría y definición positiva $\Rightarrow$ **es un producto interno válido sobre $\mathbb{R}^2$**.

In [38]:
import numpy as np

def phi(x, y):
    # Φ(x,y) = 5x₁y₁ + x₁y₂ + x₂y₁ + 3x₂y₂
    return 5*x[0]*y[0] + x[0]*y[1] + x[1]*y[0] + 3*x[1]*y[1]

def forma_cuadratica(x):
    # Φ(x,x) = 5(x₁ + x₂/5)² + (14/5)x₂²  — siempre ≥ 0
    return 5*(x[0] + x[1]/5)**2 + (14/5)*x[1]**2

# Simetría: Φ(x,y) == Φ(y,x) para vectores aleatorios
print("Simetría Φ(x,y) = Φ(y,x):")
np.random.seed(42)
for _ in range(4):
    x, y = np.random.randn(2), np.random.randn(2)
    print(f"  Φ(x,y)={phi(x,y):.6f}  Φ(y,x)={phi(y,x):.6f}  iguales: {np.isclose(phi(x,y), phi(y,x))}")

# Definición positiva: Φ(x,x) > 0 para x ≠ 0
print("\nDefinición positiva Φ(x,x) > 0:")
for _ in range(5):
    x = np.random.randn(2)
    val = phi(x, x)
    val_fc = forma_cuadratica(x)
    print(f"  x={np.round(x,3)}  Φ(x,x)={val:.6f}  forma cuadrática={val_fc:.6f}  > 0: {val > 0}")

print(f"\n¿Φ es un producto interno válido? → True")

Simetría Φ(x,y) = Φ(y,x):
  Φ(x,y)=1.643797  Φ(y,x)=1.643797  iguales: True
  Φ(x,y)=-2.937394  Φ(y,x)=-2.937394  iguales: True
  Φ(x,y)=0.296971  Φ(y,x)=0.296971  iguales: True
  Φ(x,y)=4.304815  Φ(y,x)=4.304815  iguales: True

Definición positiva Φ(x,x) > 0:
  x=[-1.013  0.314]  Φ(x,x)=4.788830  forma cuadrática=4.788830  > 0: True
  x=[-0.908 -1.412]  Φ(x,x)=12.671155  forma cuadrática=12.671155  > 0: True
  x=[ 1.466 -0.226]  Φ(x,x)=10.231739  forma cuadrática=10.231739  > 0: True
  x=[ 0.068 -1.425]  Φ(x,x)=5.920101  forma cuadrática=5.920101  > 0: True
  x=[-0.544  0.111]  Φ(x,x)=1.397906  forma cuadrática=1.397906  > 0: True

¿Φ es un producto interno válido? → True


# Segunda pregunta

Sea en $\mathbb{R}^3$ la base $G = \{(1,2,1),\,(3,0,-1),\,(-1,2,-3)\}$. Considerando los vectores en ese orden, ¿cuál es el valor de $k_3$ al aplicar Gram-Schmidt (+ normalización)?

## Respuesta: **b. $(-0.267,\;0.5345,\;-0.802)$**

El proceso de **Gram-Schmidt** toma una base cualquiera y produce una base **ortonormal** paso a paso:

$$k_i = v_i - \sum_{j=1}^{i-1} \langle v_i, u_j \rangle\, u_j \qquad u_i = \frac{k_i}{\|k_i\|}$$

---

### Paso 1

$$k_1 = v_1 = (1,2,1) \qquad \|k_1\| = \sqrt{6}$$

$$u_1 = \frac{1}{\sqrt{6}}(1,2,1)$$

---

### Paso 2

$$\langle v_2, u_1 \rangle = \frac{3\cdot1 + 0\cdot2 + (-1)\cdot1}{\sqrt{6}} = \frac{2}{\sqrt{6}}$$

$$k_2 = v_2 - \frac{2}{\sqrt{6}}\,u_1 = (3,0,-1) - \frac{2}{6}(1,2,1) = \left(\tfrac{8}{3},\,-\tfrac{2}{3},\,-\tfrac{4}{3}\right) \qquad \|k_2\| = \frac{2\sqrt{21}}{3}$$

$$u_2 = \frac{1}{\sqrt{21}}(4,-1,-2)$$

---

### Paso 3

$$\langle v_3, u_1 \rangle = \frac{-1+4-3}{\sqrt{6}} = 0 \qquad \langle v_3, u_2 \rangle = \frac{-4-2+6}{\sqrt{21}} = 0$$

Ambas proyecciones son cero, entonces:

$$k_3 = v_3 = (-1,\,2,\,-3) \qquad \|k_3\| = \sqrt{14}$$

$$\boxed{u_3 = \frac{k_3}{\|k_3\|} = \frac{(-1,\,2,\,-3)}{\sqrt{14}} \approx (-0.267,\;0.5345,\;-0.802)}$$

In [39]:
import numpy as np

v1 = np.array([1,  2,  1], dtype=float)
v2 = np.array([3,  0, -1], dtype=float)
v3 = np.array([-1, 2, -3], dtype=float)

def gram_schmidt(vectors):
    us, ks = [], []
    for v in vectors:
        k = v.copy()
        for u in us:
            k -= np.dot(v, u) * u
        ks.append(k)
        us.append(k / np.linalg.norm(k))
    return ks, us

ks, us = gram_schmidt([v1, v2, v3])

for i, (k, u) in enumerate(zip(ks, us), 1):
    print(f"k{i} = {np.round(k, 4)}")
    print(f"u{i} = {np.round(u, 4)}\n")

print(f"→ Respuesta: u3 = {np.round(us[2], 4)}")

# Verificación: base ortonormal (uᵢ·uⱼ = δᵢⱼ)
print("\nVerificación ortogonalidad (deben ser ≈ 0):")
pairs = [(0,1),(0,2),(1,2)]
for i, j in pairs:
    print(f"  u{i+1}·u{j+1} = {np.dot(us[i], us[j]):.2e}")

print("\nVerificación normalización (deben ser ≈ 1):")
for i, u in enumerate(us, 1):
    print(f"  ||u{i}|| = {np.linalg.norm(u):.6f}")

k1 = [1. 2. 1.]
u1 = [0.4082 0.8165 0.4082]

k2 = [ 2.6667 -0.6667 -1.3333]
u2 = [ 0.8729 -0.2182 -0.4364]

k3 = [-1.  2. -3.]
u3 = [-0.2673  0.5345 -0.8018]

→ Respuesta: u3 = [-0.2673  0.5345 -0.8018]

Verificación ortogonalidad (deben ser ≈ 0):
  u1·u2 = -6.08e-17
  u1·u3 = -3.28e-17
  u2·u3 = -4.26e-17

Verificación normalización (deben ser ≈ 1):
  ||u1|| = 1.000000
  ||u2|| = 1.000000
  ||u3|| = 1.000000


# Tercer pregunta

La matriz $\begin{pmatrix} 1 & 5 \\ 3 & -2 \end{pmatrix}$ es:

a. definida positiva

b. semi definida positiva

c. ninguna de las anteriores

## Respuesta: **c. ninguna de las anteriores**

### Paso 1 — Condición necesaria: simetría

Para que una matriz real sea **definida positiva** o **semi-definida positiva**, debe ser simétrica:

$$A = A^\top$$

### Paso 2 — Calcular la traspuesta

$$A = \begin{pmatrix} 1 & 5 \\ 3 & -2 \end{pmatrix} \qquad A^\top = \begin{pmatrix} 1 & 3 \\ 5 & -2 \end{pmatrix}$$

### Paso 3 — Comparar

$$A \neq A^\top \quad \text{porque} \quad a_{12} = 5 \neq 3 = a_{21}$$

La matriz **no es simétrica**, por lo tanto no puede ser definida positiva ni semi-definida positiva.

$$\boxed{\text{c. ninguna de las anteriores}}$$

In [40]:
import numpy as np

A = np.array([[1,  5],
              [3, -2]], dtype=float)

print(f"A  =\n{A}\n")
print(f"Aᵀ =\n{A.T}\n")

es_simetrica = np.allclose(A, A.T)
print(f"¿A == Aᵀ? → {es_simetrica}")
print(f"\nComo A no es simétrica → c. ninguna de las anteriores")

A  =
[[ 1.  5.]
 [ 3. -2.]]

Aᵀ =
[[ 1.  3.]
 [ 5. -2.]]

¿A == Aᵀ? → False

Como A no es simétrica → c. ninguna de las anteriores


# Cuarta pregunta

La matriz $\begin{pmatrix} 1 & -2 \\ -2 & 2 \end{pmatrix}$ es:

a. definida positiva

b. semi definida positiva

c. ninguna de las anteriores

## Respuesta: **c. ninguna de las anteriores**

### Paso 1 — Simetría

$$A = \begin{pmatrix} 1 & -2 \\ -2 & 2 \end{pmatrix} \qquad A^\top = \begin{pmatrix} 1 & -2 \\ -2 & 2 \end{pmatrix}$$

$A = A^\top$ $\checkmark$ — la matriz es simétrica, así que hay que continuar al paso 2.

---

### Paso 2 — Forma cuadrática $Q(x) = x^\top A x$

$$Q(x) = x_1(x_1 - 2x_2) + x_2(-2x_1 + 2x_2) = x_1^2 - 4x_1x_2 + 2x_2^2$$

Completando el cuadrado en $x_1$:

$$Q(x) = (x_1 - 2x_2)^2 - 4x_2^2 + 2x_2^2 = (x_1 - 2x_2)^2 - 2x_2^2$$

El segundo término es **negativo**. Eligiendo $x_1 = 2x_2$ con $x_2 \neq 0$:

$$Q(2x_2,\, x_2) = 0 - 2x_2^2 = -2x_2^2 < 0$$

$Q(x)$ puede ser negativa $\Rightarrow$ la matriz no es definida positiva ni semi-definida positiva.

$$\boxed{\text{c. ninguna de las anteriores}}$$

In [41]:
import numpy as np

A = np.array([[1, -2],
              [-2, 2]], dtype=float)

print(f"A  =\n{A}\n")
print(f"Aᵀ =\n{A.T}\n")
print(f"¿A == Aᵀ? → {np.allclose(A, A.T)}  (simétrica, continuamos)\n")

def Q(x):
    # Q(x) = x₁² - 4x₁x₂ + 2x₂² = (x₁ - 2x₂)² - 2x₂²
    return x @ A @ x

def Q_cuadrado_completo(x):
    return (x[0] - 2*x[1])**2 - 2*x[1]**2

# Contraejemplo: x = (2, 1) → Q = -2 < 0
x_contra = np.array([2.0, 1.0])
print(f"Contraejemplo: x = {x_contra}")
print(f"  Q(x) = xᵀAx                = {Q(x_contra)}")
print(f"  Q(x) = (x₁-2x₂)² - 2x₂²   = {Q_cuadrado_completo(x_contra)}")
print(f"  Q(x) < 0 → NO es definida positiva ✓\n")

print("Exploración de distintos vectores:")
tests = [np.array([1., 0.]), np.array([0., 1.]),
         np.array([2., 1.]), np.array([1., 1.]), np.array([4., 2.])]
for x in tests:
    val = Q(x)
    print(f"  x={x}  →  Q(x) = {val:7.2f}  ({'< 0 ✗' if val < 0 else '>= 0'})")

print("\n→ Q(x) toma valores negativos  ⟹  c. ninguna de las anteriores")

A  =
[[ 1. -2.]
 [-2.  2.]]

Aᵀ =
[[ 1. -2.]
 [-2.  2.]]

¿A == Aᵀ? → True  (simétrica, continuamos)

Contraejemplo: x = [2. 1.]
  Q(x) = xᵀAx                = -2.0
  Q(x) = (x₁-2x₂)² - 2x₂²   = -2.0
  Q(x) < 0 → NO es definida positiva ✓

Exploración de distintos vectores:
  x=[1. 0.]  →  Q(x) =    1.00  (>= 0)
  x=[0. 1.]  →  Q(x) =    2.00  (>= 0)
  x=[2. 1.]  →  Q(x) =   -2.00  (< 0 ✗)
  x=[1. 1.]  →  Q(x) =   -1.00  (< 0 ✗)
  x=[4. 2.]  →  Q(x) =   -8.00  (< 0 ✗)

→ Q(x) toma valores negativos  ⟹  c. ninguna de las anteriores
